### PR TITLE
Added divider to dropdown

### PR DESCRIPTION
**Pull request by nathanbedford**
Feedback welcome :)

### CODE REVIEW

**Comment by nathanbedford** [comment]
You can review the demo running here:
https://ng-wizi-bulma-15.review.bedfordsoftware.ml/dropdown

**Comment by nathanbedford** [comment]
I'd be happy to add a code snippet using the 'nwb-doc-preview' component you are using elsewhere, that's really nice.

**Comment by JumBay** [comment]
Thx for the PR.
Could you please merge master to your branch first and don't increment the version number in all package.json. 

Also, I don't get why you output `option.divder` here: https://github.com/nathanbedford/ng-wizi-bulma/blob/271f2eb8c1c31915151818a79065a7a019bab4ce/projects/ng-wizi-bulma/src/lib/dropdown/dropdown.component.html#L25
Otherwise, everything is fine and would be merged.

You can include the fix for #14 too. 

Thx

**Comment by nathanbedford** [comment]
* merged master in
* removed my "option.divider" debug output I accidentally left in there (good catch)
* Added fix for #14 too

**Comment by JumBay** [comment]
Thx.
I've published it on npm

**Pull request merged**
