### PR TITLE
added some tabs+demo

### PR DESCRIPTION
**Pull request by TomzOk**

### CODE REVIEW

**Comment by JumBay** [comment]
Thanks for you PR, I just reviewed it and you should do some changes before we can accept it:
- Use element-name for your components instead of attribute name
- You cannot rely on the tab's label to select it, instead you should use the tab's id or another unique attribute like its name. 
- In the demo part, provide an exemple on how to select a tab without clicking on it (with a button for instance).
- Add a type attribute to handle tabs style https://bulma.io/documentation/components/tabs/#styles
- For icons, you shouldn't force the use of font awesome, but do like https://bulma.io/documentation/elements/icon/, so let the user type the class he wants like `fas fa-home` or `mdi mdi-bell`
- Remove unused code

**Comment by TomzOk** [comment]
Hi thanks for review.

I updated demo to include button, removed assumptions from icon package, parent element called by element name, and added the bulma styles (rounded/fullwidth/etc).

I did not update the nwb-tabs-item attribute or change the selection parameter yet because not sure of best strategy.  I sort of like using the label as it requires less code and attributes to pass from the caller.  Maybe there are examples of when you would want tabs to have the same label?

**Comment by JumBay** [comment]
Thanks.

It's not about having the same label, but rather having dynamic labels from translation for example. You could set only the label attribute and let the app set ids automatically in the order you added the tabs and then you'll be able to select the tab with the right id. If you want more control then set an unique name or enter the id manually both are good (I prefer the ID way)

**Comment by TomzOk** [comment]
I see.  Buefy seems to use index.  Is that alright here?  That can minimize attribute parameters but forces dynamic tabs to use an array.

ie:
<nwb-tabs-item *ngFor="let tab of tabs" [label]="tab.label">
  <content-here></content-here>
</nwb-tabs-item>

**Comment by TomzOk** [comment]
nwb-tabs-item is now an element directive with a [label]= attribute, and is selected with an index.  The selection property is decoupled from the label now so if want an id attribute or other it can changed pretty easily.

**Comment by JumBay** [comment]
I did merge your branch. I did some refactor too

**Pull request merged**
